{% set name = "dtool_overlay" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-overlay/dtool-overlay-{{ version }}.tar.gz
  sha256: ac10507de5f529219a8e3307e21d6492ed1876ef06669783f934c9fbaa03dda7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - dtool_cli
    - dtoolcore
    - parse
    - python >=3.6

test:
  imports:
    - dtool_overlay
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtool-overlay
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: dtool CLI utilities for working with per item metadata
  description: |
    dtool CLI utilities for working with per item metadata
  doc_url: https://github.com/jic-dtool/dtool-overlay
  dev_url: https://github.com/jic-dtool/dtool-overlay

extra:
  recipe-maintainers:
    - jan-janssen
    - tjelvar-olsson
